/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitapthuchanh5_20521086;

import com.microsoft.sqlserver.jdbc.SQLServerStatement;
import java.awt.event.KeyEvent;
import com.toedter.calendar.JDateChooser;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author kyanh
 */
public class DatLichKham extends javax.swing.JFrame {

    /**
     * Creates new form DatLichKham
     */
    public DatLichKham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDatLich = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaBN = new javax.swing.JTextField();
        txtYeuCau = new javax.swing.JTextField();
        lbTenBN = new javax.swing.JLabel();
        dateNgayKham = new com.toedter.calendar.JDateChooser();
        cboxTenBS = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDatLich.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDatLich.setText("Đặt lịch khám");
        btnDatLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLichActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Mã bệnh nhân");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tên bệnh nhân");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ngày khám");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Yêu cầu khám");

        txtMaBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaBNKeyPressed(evt);
            }
        });

        txtYeuCau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbTenBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dateNgayKham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cboxTenBS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboxTenBS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Bác sĩ khám");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtYeuCau, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dateNgayKham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxTenBS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDatLich, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTenBN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateNgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtYeuCau, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboxTenBS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDatLich, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LayTenBS()
    {
        cboxTenBS.removeAllItems();
        
        try{
            Connection con = null;
            con = SQLConnection.getSQLConnection();
            String SQL = "SELECT TENBS FROM BACSI";
            SQLServerStatement state = (SQLServerStatement) con.createStatement(); 
            ResultSet rs = state.executeQuery(SQL);
            while(rs.next())
            {
                String ten = rs.getString(1);
                cboxTenBS.addItem(ten);
            }
        }catch (Exception e){
            System.out.print("Lỗi " + e);
        }
        //setVisible(true);
    }
    
    private void KhoiTaoFrame()
    {
        txtMaBN.setText(null);
        lbTenBN.setText(null);
        dateNgayKham.setCalendar(null);
        txtYeuCau.setText(null);
        LayTenBS();
        setVisible(true);
    }
    
    private String LayMaBS(String tenbs)
    {
        String mabs=null;
        try{
            Connection con = null;
            con = SQLConnection.getSQLConnection();
            String SQL = "SELECT MABS FROM BACSI WHERE TENBS=?";
            PreparedStatement State = con.prepareStatement(SQL); 
            State.setString(1,tenbs);
            ResultSet rs = State.executeQuery();   
            
            while(rs.next())
            {
                mabs = rs.getString(1);
            }
            return mabs;
        }catch (Exception e){
            System.out.print("Lỗi tai lấy mã bác sĩ " + e);
            return null;
        }
    }
    
    private Boolean KiemTraNhap(String mabn, JDateChooser ngaykham)
    {
        //kiểm tra nhập đủ
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try{
            String ngkham = sdf.format(ngaykham.getDate());
        }catch(Exception ex)
        {
            return false;
        }
        
        if (mabn.isEmpty())
            return false;
        //kiểm tra nhập đúng
        
//        if (mabn.length() != 4)
//        try{
//            Integer.parseInt(dt);
//            if (ma.length()!=4 || ten.length()>20 || dchi.length()>50 || dt.length()>10)
//                return false;
//        }catch(Exception ex){
//            return false;
//        } 
        return true;
    }
            
    
    private void btnDatLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLichActionPerformed
        if (KiemTraNhap(txtMaBN.getText(),dateNgayKham) == true)
        {
            String mabn = txtMaBN.getText();
            String yeucau = txtYeuCau.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
            String ngaykham = sdf.format(dateNgayKham.getDate());
            String mabs = LayMaBS(cboxTenBS.getSelectedItem().toString());
            try{
                Connection conn = SQLConnection.getSQLConnection();
                String sql = "INSERT INTO KHAMBENH(MABN,MABS,NGAYKHAM,YEUCAUKHAM,THANHTOAN) VALUES(?,?,?,?,0)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1,mabn);
                ps.setString(2, mabs);
                ps.setString(3,ngaykham);
                ps.setString(4,yeucau);
                int rs = ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Đặt lịch khám thành công!");
    //            lbTenBN.setText("");
    //            txtMaBN.setText("");
    //            LayTenBS();
    //            txtYeuCau.setText("");
                KhoiTaoFrame();
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, "Lỗi tại đặt lịch" +ex);
            }
        }
        else
            JOptionPane.showMessageDialog(this,"Nhập thông tin không đầy đủ hoặc sai kiểu dữ liệu!","Không thành công!",JOptionPane.ERROR_MESSAGE);

        
    }//GEN-LAST:event_btnDatLichActionPerformed

    
    
    private void txtMaBNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaBNKeyPressed
        String mabn = txtMaBN.getText();
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
                Connection conn = SQLConnection.getSQLConnection();
                String SQL = "SELECT TENBN FROM BENHNHAN"
                + " WHERE MABN = ?";
                PreparedStatement ps = conn.prepareStatement(SQL);
                ps.setString(1,mabn);
                ResultSet rs = ps.executeQuery();
                
                String ten = null;
                while (rs.next()) {
                    ten = rs.getString("TENBN");
                        lbTenBN.setText(rs.getString("TENBN"));
                }
                
                if (ten==null)
                    {
                        lbTenBN.setText(""); 
                        JOptionPane.showMessageDialog(this,"Mã bệnh nhân '"+mabn+"' chưa đăng ký","Lỗi",JOptionPane.ERROR_MESSAGE);
                    }
            }
            catch(Exception ex) {
                System.out.print(ex);
//JOptionPane.showMessageDialog(this,"Mã không đúng kiểu dữ liệu int","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtMaBNKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatLichKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatLichKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatLichKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatLichKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatLichKham().KhoiTaoFrame();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatLich;
    private javax.swing.JComboBox<String> cboxTenBS;
    private com.toedter.calendar.JDateChooser dateNgayKham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbTenBN;
    private javax.swing.JTextField txtMaBN;
    private javax.swing.JTextField txtYeuCau;
    // End of variables declaration//GEN-END:variables
}
