/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitapthuchanh5_20521086;

import com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author kyanh
 */
public class A_ThemNCC extends javax.swing.JFrame {

    public A_ThemNCC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTenNCC = new javax.swing.JLabel();
        lbDC = new javax.swing.JLabel();
        lbDT = new javax.swing.JLabel();
        lbMail = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtfieldTenNCC = new javax.swing.JTextField();
        txtfieldDC = new javax.swing.JTextField();
        txtfieldDT = new javax.swing.JTextField();
        txtfieldMail = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 4, 4));

        lbTenNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTenNCC.setText("Tên nhà cung cấp");
        jPanel1.add(lbTenNCC);

        lbDC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDC.setText("Địa chỉ");
        jPanel1.add(lbDC);

        lbDT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDT.setText("Điện thoại");
        jPanel1.add(lbDT);

        lbMail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMail.setText("Email");
        jPanel1.add(lbMail);

        jPanel2.setLayout(new java.awt.GridLayout(4, 1, 4, 2));

        txtfieldTenNCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtfieldTenNCC);

        txtfieldDC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtfieldDC);

        txtfieldDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtfieldDT);

        txtfieldMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtfieldMail);

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Boolean KiemTraNhap(String ten, String diachi, String dthoai, String mail)
    {
        //kiểm tra nhập đủ
        if (ten.isEmpty() || diachi.isEmpty()||dthoai.isEmpty()||mail.isEmpty())
            return false;
        //kiểm tra nhập đúng
        try{
            int so = Integer.parseInt(dthoai);
            if (ten.length()>40 || diachi.length()>40 || dthoai.length()>10 || mail.length()>30)
                return false;
        }catch(Exception ex){
            //bắt exception khi dthoai không nhập số mà nhập chữ/ ký tự đặc biệt
            return false;
        } 
        return true;
    }
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String ten = txtfieldTenNCC.getText();
        String diachi = txtfieldDC.getText();
        String sdt = txtfieldDT.getText();
        String email = txtfieldMail.getText();
        
        if(KiemTraNhap(ten,diachi,sdt,email) == true)
        {
            try{
                Connection conn = null;
                conn = CheckSQLConnection.getMyConnection();

                String SQL = "INSERT INTO NHACC(TENNCC,DIACHI,DTHOAI,EMAIL) VALUES (?,?,?,?)";

                SQLServerPreparedStatement ps = (SQLServerPreparedStatement) conn.prepareStatement(SQL); 
                ps.setString(1,ten);
                ps.setString(2,diachi);
                ps.setString(3,sdt);
                ps.setString(4,email);

                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Tạo thành công");
                
            }catch (Exception ex){
                JOptionPane.showMessageDialog(this,"Không thể tạo nhà cung cấp","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(this,"Nhập không đầy đủ hoặc nhập sai kiểu dữ liệu!","Lỗi",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_ThemNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_ThemNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_ThemNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_ThemNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_ThemNCC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbDC;
    private javax.swing.JLabel lbDT;
    private javax.swing.JLabel lbMail;
    private javax.swing.JLabel lbTenNCC;
    private javax.swing.JTextField txtfieldDC;
    private javax.swing.JTextField txtfieldDT;
    private javax.swing.JTextField txtfieldMail;
    private javax.swing.JTextField txtfieldTenNCC;
    // End of variables declaration//GEN-END:variables
}
